# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch
import torch
# Create random tensor
rand_a = torch.rand(size=(7,7))
print(rand_a)

tensor([[0.4110, 0.4177, 0.1209, 0.9701, 0.3964, 0.8781, 0.1722],
        [0.5291, 0.1265, 0.6301, 0.9752, 0.5688, 0.2504, 0.8705],
        [0.1745, 0.4629, 0.1803, 0.2755, 0.5099, 0.9532, 0.0011],
        [0.2376, 0.6903, 0.6351, 0.3897, 0.1228, 0.3598, 0.3723],
        [0.4181, 0.1031, 0.3531, 0.6269, 0.8408, 0.0096, 0.3476],
        [0.1047, 0.1751, 0.0610, 0.6395, 0.3548, 0.8270, 0.2975],
        [0.7473, 0.3184, 0.0479, 0.3422, 0.6146, 0.7386, 0.6850]])


### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [3]:
# Create another random tensor
rand_b = torch.rand(size=(1,7))
print(rand_b)
# Perform matrix multiplication 
print(rand_a @ rand_b.T)

tensor([[0.9933, 0.3580, 0.2490, 0.6433, 0.0293, 0.5946, 0.1455]])
tensor([[1.7707],
        [1.6472],
        [1.1431],
        [1.1637],
        [1.0243],
        [1.1386],
        [1.6452]])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [4]:
# Set manual seed
SEED = 0
torch.manual_seed(SEED)
# Create two random tensors
rand_c = torch.rand(size=(7,7))
rand_d = torch.rand(size=(1,7))
# Matrix multiply tensors
rand_c @ rand_d.T

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [5]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [6]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

# Create two random tensors on GPU
rand_e = torch.rand(size=(2,3)).to(device)
rand_f = torch.rand(size=(2,3)).to(device)
rand_e, rand_f

Device: cpu


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]]),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]]))

In [7]:
# Set random seed
torch.cuda.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

# Create two random tensors on GPU
"""结论：torch的CPU和GPU有独立的随机数生成器，需要单独设置"""
rand_e1 = torch.rand(size=(2,3),device=device)
rand_f1 = torch.rand(size=(2,3),device=device)
rand_e1, rand_f1



Device: cpu


(tensor([[0.7749, 0.8208, 0.2793],
         [0.6817, 0.2837, 0.6567]]),
 tensor([[0.2388, 0.7313, 0.6012],
         [0.3043, 0.2548, 0.6294]]))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [8]:
# Perform matmul on tensor_A and tensor_B
# torch.matmul(rand_e ,rand_f.T)
rand_g = rand_e @ rand_f.T
print(rand_g, rand_g.shape)

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]]) torch.Size([2, 2])


### 8. Find the maximum and minimum values of the output of 7.

In [9]:
# Find max
max = torch.max(rand_g)
# Find min
min = torch.min(rand_g)
max, min

(tensor(0.5617), tensor(0.3647))

### 9. Find the maximum and minimum index values of the output of 7.

In [10]:
# Find arg max
argmax = torch.argmax(rand_g)

# Find arg min
argmin = torch.argmin(rand_g)

argmax, argmin

(tensor(3), tensor(0))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [11]:
# Set seed
torch.manual_seed(7)

# Create random tensor
rand_h = torch.rand(size=(1,1,1,10))
print(rand_h, rand_h.shape)

# Remove single dimensions
rand_i = rand_h.squeeze()
print(rand_i, rand_i.shape)

# Print out tensors and their shapes
# see above

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])


In [ ]:
# check if apple silicon version works
torch.backends.mps.is_available()

True

In [15]:
# Set device type
device = "mps" if torch.backends.mps.is_available() else "cpu"
print(device)

rand_j = torch.rand(size=(2,2)).to(device=device)
print(rand_j)

mps
tensor([[0.8549, 0.5509],
        [0.2868, 0.2063]], device='mps:0')
