# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [13]:
# Import torch
import torch
# Create random tensor
rand_a = torch.rand(size=(7,7))
print(rand_a)

tensor([[0.4147, 0.6149, 0.0185, 0.2428, 0.5979, 0.5017, 0.3081],
        [0.5340, 0.6230, 0.2981, 0.7955, 0.4119, 0.1306, 0.5593],
        [0.5933, 0.0982, 0.1070, 0.0344, 0.1422, 0.2582, 0.6249],
        [0.2015, 0.8840, 0.2940, 0.6334, 0.8706, 0.8314, 0.1944],
        [0.9965, 0.5010, 0.4600, 0.2687, 0.2588, 0.2761, 0.9668],
        [0.1968, 0.8535, 0.9372, 0.5687, 0.1386, 0.7998, 0.8860],
        [0.9987, 0.0444, 0.1778, 0.0148, 0.0616, 0.9068, 0.4263]])


### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [14]:
# Create another random tensor
rand_b = torch.rand(size=(1,7))
print(rand_b)
# Perform matrix multiplication 
print(rand_a @ rand_b.T)

tensor([[0.9175, 0.9372, 0.2812, 0.0297, 0.8333, 0.4543, 0.3550]])
tensor([[1.8047],
        [1.7824],
        [1.1251],
        [2.2871],
        [2.2054],
        [2.0542],
        [1.6229]])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [16]:
# Set manual seed
SEED = 0
torch.manual_seed(SEED)
# Create two random tensors
rand_c = torch.rand(size=(7,7))
rand_d = torch.rand(size=(1,7))
# Matrix multiply tensors
rand_c @ rand_d.T

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [ ]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [33]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

# Create two random tensors on GPU
rand_e = torch.rand(size=(2,3)).to(device)
rand_f = torch.rand(size=(2,3)).to(device)
rand_e, rand_f

Device: cuda


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))

In [34]:
# Set random seed
torch.cuda.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

# Create two random tensors on GPU
"""结论：torch的CPU和GPU有独立的随机数生成器，需要单独设置"""
rand_e1 = torch.rand(size=(2,3),device=device)
rand_f1 = torch.rand(size=(2,3),device=device)
rand_e1, rand_f1



Device: cuda


(tensor([[0.1272, 0.8167, 0.5440],
         [0.6601, 0.2721, 0.9737]], device='cuda:0'),
 tensor([[0.6208, 0.0276, 0.3255],
         [0.1114, 0.6812, 0.3608]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [37]:
# Perform matmul on tensor_A and tensor_B
# torch.matmul(rand_e ,rand_f.T)
rand_g = rand_e @ rand_f.T
print(rand_g, rand_g.shape)

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0') torch.Size([2, 2])


### 8. Find the maximum and minimum values of the output of 7.

In [ ]:
# Find max
max = torch.max(rand_g)
# Find min
min = torch.min(rand_g)
max, min

tensor(0.5617, device='cuda:0')
tensor(0.3647, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [41]:
# Find arg max
argmax = torch.argmax(rand_g)

# Find arg min
argmin = torch.argmin(rand_g)

argmax, argmin

(tensor(3, device='cuda:0'), tensor(0, device='cuda:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [ ]:
# Set seed
torch.manual_seed(7)

# Create random tensor
rand_h = torch.rand(size=(1,1,1,10))
print(rand_h, rand_h.shape)

# Remove single dimensions
rand_i = rand_h.squeeze()
print(rand_i, rand_i.shape)

# Print out tensors and their shapes
# see above

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
